version: '3'

services:
  ui:
    build: ./ui/LeadManagementSPA 
    environment:
      API_URL: http://localhost:8080
    ports:
      - "8100:8100"
    volumes:
      - ./ui/LeadManagementSPA:/opt/ui
      - /opt/ui/node_modules
    
  server:
    build: ./server
    environment:
      NODE_ENV: development
    links:
      - database:database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/server
    
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d